name: Release

on:
  workflow_dispatch

permissions:
  contents: write

jobs:
  publish-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install vpk
        run: dotnet tool install -g vpk --version 0.0.1535-gb21da2a

      - name: Get version
        id: version
        shell: pwsh
        run: |
          [xml]$props = Get-Content Publish.props
          $version = ($props.Project.PropertyGroup | Where-Object { $_.Version } | Select-Object -First 1).Version
          echo "version=$version" >> $env:GITHUB_OUTPUT

      - name: Publish
        run: dotnet publish -c Release -r win-x64

      - name: Download previous release
        run: vpk download github --repoUrl https://github.com/wrdg/DayZExtract --token ${{ secrets.GITHUB_TOKEN }} -o releases
        continue-on-error: true

      - name: Pack
        run: vpk pack -u DayZExtract -v ${{ steps.version.outputs.version }} -o releases -p publish --mainExe DayZExtract.exe --packAuthors Wardog --msi --instLocation PerUser

      - name: Upload
        run: vpk upload github --repoUrl https://github.com/wrdg/DayZExtract --token ${{ secrets.GITHUB_TOKEN }} -o releases --publish --tag v${{ steps.version.outputs.version }}
